services:
  db:
    image: postgres:16
    container_name: tickets-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Raj@1234
      POSTGRES_DB: tickets
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tickets"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: